sudo: required
services:
  - docker
language: bash
env:
  matrix:
    - MAKE_TARGET=arm64-debian
    - MAKE_TARGET=armhf-debian
    - MAKE_TARGET=armhf-raspbian
script:
  - make shellcheck
  - HYPRIOT_OS_VERSION=${TRAVIS_TAG} make ${MAKE_TARGET}
