sudo: required
services:
  - docker
language: bash
env:
  global:
    - HYPRIOT_HOSTNAME=prisms-gateway
    - HYPRIOT_USERNAME=prisms
    - HYPRIOT_PASSWORD=clean_AIR?
  matrix:
    - MAKE_TARGET=armhf-raspbian
script:
  - make shellcheck
  - HYPRIOT_OS_VERSION=${TRAVIS_TAG} make ${MAKE_TARGET}
branches:
  only:
    - master
    - "/^v\\d.*$/"
deploy:
  provider: releases
  skip_cleanup: true
  file:
    - rootfs-${MAKE_TARGET}-${TRAVIS_TAG}.tar.gz
    - rootfs-${MAKE_TARGET}-${TRAVIS_TAG}.tar.gz.sha256
  on:
    tags: true
    repo: VDL-PRISM/os-rootfs
  api_key:
    secure: Ye2JqZl+RZktpIA8ISD8obBBKvOA7lr3txQbVjZsJubsMUnMUU8WxcD5gcMJY7hdz47yF09TczcmPWfBHiV1nwjcKNPVOkLealf+mS8F97MhLm/jXGpDg7Vl3BmXhcx6JF21QRlriIBNqqvEUfXUO738K/PV/NKrwDMw9kAD6zwb9PFbFroDL/4n8cecGx9H02xcmEgFaE7E1aVh4yIJmZSl20/tiqUy0Xl7lrILK1OH0ALwOI7ISrrCE5YG/XQLri5IBOIerL7m3DPaA93Hsou8ZPHXJWa6tNqxei88QTztl2cav+MUY74GdNsdNcTGk2YNk3rIUuo8Rs5xkmjQUUKh1ouf++mqyjpLzlQtDKMIqXOcYisGGPqIwTJGfUekB6qhTZXUTauEATa/rDFf+Ot6YweNUHtR6Mhb8MRef8KIwSbqJlhSJyArleAOtwJi2bxhRlk/ZKqhe8Oh45l376wamiEqS8s45fRLmV3Jvxd0Zwehealcv2laU0ZIynlmElhdMLRyYHG1iTMTnr2A5T22ArJ6Mcgm1nmpOpUYDodmVQhkvDxyOVWNcMcMp0wTXsncjDq6Dc6AMrmRrESmOd4hzsQZppTX2FXGy+gok2jxHujLZyfqa4m0SgVSfCFJd09R8wBbhOC4RRjNMbmH0i2ws6APOYDYUl1D+VcIFqU=
